### ISSUE TITLE
Reference to AbstractSpecies type broken due to deprecated enzymeml-specifications

### ISSUE THREAD

**Issue by torogi94** [FAIRChemistry/MTPHandler#18]
MTPHandler is currently not working, as `Plate` references `https://github.com/EnzymeML/enzymeml-specifications.git@AbstractSpecies` as the type of its field `species`.  
In `enzymeml-specifications`, the `AbstractSpecies` contains an XML declaration that is deprecated and broken since upgrading sdRDM to pydantic v2.  
Thus, for MTPHandler to work again, `enzymeml-specifications` has to be updated.

**Comment by haeussma** [comment]
Refactored data model and removed the AbstractSpecies type
